/**
 * Primary v2 annotation, expressed as reviewable source phrases rather than
 * hand-counted offsets. Running this resolves each phrase to an exact UTF-16
 * span, validates the finished artifact, and writes the immutable JSON layer.
 */
import { readFileSync } from "node:fs";
import { validateAnnotations, type Act, type Annotation, type Evidence, type SourceMessage } from "./court-v2.ts";

const ROOT = `${import.meta.dir}/../../plans/court-audit`;
const source = JSON.parse(readFileSync(`${ROOT}/audit-source.json`,"utf8")) as Array<SourceMessage & {from:string;to:string}>;
const byId = new Map(source.map((x)=>[x.id,x]));
const analysed = [8,9,35,36,37,38,39,40,70,71,95,97,109,110,111,112,122,132,133,136,141,146,154,155,161,243,248,249,262,263,267,268,269,275,279,284,285,288,289,290,291,292,295,323,399];
type T = Act["type"];
type A = [T,string,Partial<Act>?];
type Spec = { acts?:A[]; hazards?:string[]; provenance?:Array<["reported_third_party"|"inferred_signal",string]>; declarations?:Array<[string,string|undefined,boolean]>; responses?:Array<[number,any,string]>; outcomes?:Array<[number,any,number,string]>; caveats?:string[] };

const S:Record<number,Spec> = {
  8:{acts:[["question","Shout if you have uncommitted work",{responsibility:{kind:"assigned",actor:"traffic-4b"}}]]},
  9:{acts:[["grant","go ahead on .claude/hooks/presence/*",{anchors:[{kind:"file",value:".claude/hooks/presence/*"}]}]],caveats:["stored from_name is known unreliable; body self-identifies traffic-4b"]},
  35:{acts:[["grant","go ahead there",{anchors:[{kind:"file",value:"test/"}]}],["request","skip those until it confirms",{responsibility:{kind:"assigned",actor:"traffic-22"},condition:{handling:"resurface_on_related_event",text:"until water agent confirms",anchors:[{kind:"file",value:"test/water*.ts"}]}}],["request","do not rename them",{responsibility:{kind:"assigned",actor:"traffic-22"}}],["request","Check 'bun ~/.claude/agent-presence/bin/cli.ts who' for live claims before each batch",{responsibility:{kind:"assigned",actor:"traffic-22"}}]],hazards:["water-sim-timberborn-7f has UNCOMMITTED edits","puppeteer scripts must NOT have .test.ts"]},
  36:{acts:[["grant","go ahead",{anchors:[{kind:"file",value:"test/"}]}],["promise","I'll be adding test/strokeChains.test.ts",{commitmentMode:"perform"}],["question","tell me the target folder for net/adapter tests",{responsibility:{kind:"assigned",actor:"traffic-c9"},condition:{handling:"manual",text:"target folder supplied"}}]],hazards:["keep them discoverable by the .test.ts suffix"]},
  37:{acts:[["request","Please SKIP the water files for now",{responsibility:{kind:"assigned",actor:"traffic-22"},constraints:["test/water*.ts and test/watersim.test.ts"]}],["promise","I'll ping you when P3 lands",{commitmentMode:"perform",condition:{handling:"automatic",text:"when P3 lands",anchors:[{kind:"work_item",value:"P3"}]}}]],hazards:["a git mv underneath would collide"],outcomes:[[1,"fulfilled",95,"test/water*.ts are all yours now"],[2,"fulfilled",95,"P3 has landed"]]},
  38:{acts:[["grant","move freely",{anchors:[{kind:"file",value:"test/"}]}],["promise","I'm adding ONE new file",{commitmentMode:"perform"}],["question","tell me the folder",{responsibility:{kind:"assigned",actor:"traffic-22"}}]],outcomes:[[2,"fulfilled",70,"test/camera.test.ts now exists"],[3,"fulfilled",71,"put it at test/unit/render/camera.test.ts"]]},
  39:{acts:[["question","What does 'pwd' say in your session?",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"}}],["request","reply to it directly if you want those skipped",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"},condition:{handling:"manual",text:"if you want those skipped"}}]],hazards:["the presence roster","about to 'git mv' files"],outcomes:[[1,"fulfilled",40,"pwd = I:/Projects/Traffic/.claude/worktrees/water-sim-timberborn"],[2,"fulfilled",40,"already replied asking it to skip test/water*.ts"]]},
  40:{acts:[["correction","the roster is recording the wrong tree for me",{correctionType:"implementation_correction",target:"presence roster"}]],provenance:[["reported_third_party","already replied asking it to skip test/water*.ts"]],responses:[[39,"answer","pwd = I:/Projects/Traffic/.claude/worktrees/water-sim-timberborn"]]},
  70:{acts:[["question","Want me to git mv it into a folder myself",{responsibility:{kind:"assigned",actor:"traffic-22"}}],["promise","Tell me the path and I'll move it",{commitmentMode:"perform",condition:{handling:"resurface_on_related_event",text:"path supplied"}}],["promise","otherwise I'll leave it at root for you",{commitmentMode:"refrain",condition:{handling:"manual",text:"recipient does not supply a path"}}]],outcomes:[[1,"fulfilled",71,"put it at test/unit/render/camera.test.ts"],[2,"unassessable",71,"move it yourself"]]},
  71:{acts:[["handoff","move it yourself",{responsibility:{kind:"assigned",actor:"traffic-07"},target:"test/camera.test.ts",constraints:["test/unit/render/camera.test.ts","imports must be '../../../src/...' (not '../src/...')"]}],["inform","Layout: test/unit/<domain>/ for *.test.ts"]],responses:[[70,"answer","put it at test/unit/render/camera.test.ts"]]},
  95:{acts:[["grant","test/water*.ts are all yours now",{anchors:[{kind:"file",value:"test/water*.ts"}]}],["request","ping me before you move them there",{responsibility:{kind:"assigned",actor:"traffic-22"},condition:{handling:"resurface_on_related_event",text:"before main-tree move",anchors:[{kind:"file",value:"test/water*.ts"}]}}]],hazards:["we won't collide until I merge"]},
  97:{acts:[["promise","I will NOT move your water files",{commitmentMode:"refrain",condition:{handling:"automatic",text:"until P3 merge",anchors:[{kind:"work_item",value:"P3"}]} }],["handoff","When you merge P3, move them yourself",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"},condition:{handling:"automatic",text:"when P3 merges",anchors:[{kind:"work_item",value:"P3"}]}}]],hazards:["IMPORTANT depth change"]},
  109:{acts:[["question","are you mid-flight on src/sim/water/flow.ts",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"}}],["question","should I wait, or work on master now?",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"}}],["promise","I'll stay off sources.ts, water.ts and the audit doc",{commitmentMode:"refrain"}]],outcomes:[[1,"fulfilled",110,"I am mid-flight RIGHT NOW on exactly your list"],[2,"fulfilled",110,"please hold on the sim-side files for now"],[3,"unassessable",110,"yes, this collides"]]},
  110:{acts:[["request","please hold on the sim-side files for now",{responsibility:{kind:"assigned",actor:"traffic-aa"}}],["proposal","Start on the ones I am NOT in"],["promise","until I ping you",{commitmentMode:"perform",condition:{handling:"manual",text:"bug fix lands"}}]],hazards:["A concurrent rewrite of those functions","wake epsilon is EXACTLY ZERO"],outcomes:[[1,"fulfilled",111,"holding off flow.ts/activeSet.ts/waterSim.ts entirely"],[2,"fulfilled",111,"I'll work in src/render/ground/waterRules.ts"],[3,"fulfilled",136,"ALL CLEAR"]]},
  111:{acts:[["promise","holding off flow.ts/activeSet.ts/waterSim.ts entirely",{commitmentMode:"refrain"}],["promise","I'll apply it then",{commitmentMode:"perform",condition:{handling:"automatic",text:"when peer lands fix",anchors:[{kind:"commit",value:"peer water fix"}]}}],["question","say so and I'll go ahead",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"},condition:{handling:"manual",text:"fix touches scheduling only"}}]],hazards:["packBand LIVES in waterTexture.ts"]},
  112:{acts:[["correction","that was my error",{correctionType:"self_erratum",target:"packBand clearance"}],["grant","go ahead on packBand now",{constraints:["keep your change INSIDE packBand/fillRow","do not reorder anything in drain() or the pending queue"],anchors:[{kind:"file",value:"src/render/ground/waterTexture.ts#packBand"}]}],["request","stage it and ping me instead",{responsibility:{kind:"assigned",actor:"traffic-aa"},condition:{handling:"manual",text:"packBand win needs drain change"}}],["promise","I will ping you the moment it lands on master",{commitmentMode:"perform",condition:{handling:"automatic",text:"commit reachable on master",anchors:[{kind:"commit",value:"fix commit"}]}}]],hazards:["rolling three-row buffer MUST stay Float64Array","baseline may move under you"],outcomes:[[2,"fulfilled",122,"Stayed strictly inside packBand/fillRow"],[4,"fulfilled",136,"ALL CLEAR"]]},
  122:{acts:[["request","merge/rebase before your fix lands",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"}}],["promise","Standing by on flow.ts/activeSet.ts/waterSim.ts",{commitmentMode:"refrain"}]],hazards:["timing profile just changed by ~5x","constructor-order change"]},
  132:{acts:[["request","tell me which way you went",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"}}],["promise","I'll re-apply my table on top",{commitmentMode:"perform",condition:{handling:"manual",text:"peer takes own conflicting block"}}]],hazards:["merge conflict you're walking into"],outcomes:[[1,"fulfilled",133,"no conflict"],[2,"unassessable",133,"we edited DIFFERENT sections"]]},
  133:{acts:[["grant","the sim kernel (sections 1/4/5) is yours as soon as that lands",{anchors:[{kind:"other",value:"WATER_HOT_FUNCTIONS sections 1/4/5"}]}],["promise","I'll ping you the commit",{commitmentMode:"perform",condition:{handling:"automatic",text:"commit merged",anchors:[{kind:"commit",value:"water fix"}]}}]],hazards:["Anything writing depthM from outside the sim MUST call it","frame replay now calls ackShown()"],responses:[[132,"answer","no conflict"]],outcomes:[[2,"fulfilled",136,"Merged to master as 9addb42"]]},
  136:{acts:[["grant","ALL CLEAR — the sim kernel is yours",{anchors:[{kind:"other",value:"sim kernel"}]}],["request","keep that split",{responsibility:{kind:"assigned",actor:"traffic-aa"},condition:{handling:"automatic",text:"if accessors are micro-optimized",anchors:[{kind:"other",value:"accessors"}]}}],["proposal","Worth running that bench alongside wateractive",{condition:{handling:"resurface_on_related_event",text:"when kernel is touched"}}],["request","re-baseline before/after numbers off 9addb42",{responsibility:{kind:"assigned",actor:"traffic-aa"}}]],hazards:["reverting surfaceAt to the live field is a real regression"]},
  141:{acts:[["correction","caught a REAL bug of mine",{correctionType:"implementation_correction",target:"liveFlowArrays fast path"}],["question","If you'd rather it stayed private",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"}}],["promise","I'll rework it",{commitmentMode:"perform",condition:{handling:"manual",text:"recipient prefers accessor"}}],["proposal","waterbacktrack belongs in WATER_HOT_FUNCTIONS' bench table"]],responses:[[136,"accept","Taking the sim kernel now"]]},
  146:{acts:[["question","If you're back in waterSim.ts for something new, tell me what",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"},condition:{handling:"resurface_on_related_event",text:"editing-file versus stale-claim branches",branch:"stale claim: ignore; active edit: answer and activate refrain",anchors:[{kind:"file",value:"src/sim/water/waterSim.ts"}]}}],["promise","I'll stay out",{commitmentMode:"refrain",condition:{handling:"manual",text:"recipient confirms active edit"}}],["request","Run it if you touch the kernel",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"},condition:{handling:"resurface_on_related_event",text:"kernel touched",anchors:[{kind:"test",value:"test/bench/waterkernelref.ts"}]}}],["correction","worth EXACTLY NOTHING per tick",{correctionType:"self_erratum",target:"flux optimization expectation"}]],hazards:["wateractive.ts CANNOT catch a change inside fluxCell/depthCell"]},
  154:{acts:[["request","rebase before you edit",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"}}],["request","Run it if you change anything on the upload path",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-7f"},condition:{handling:"automatic",text:"upload path changes",anchors:[{kind:"test",value:"test/browser/waterUpload.ts"}]}}]],hazards:["NEW LIVE TRAP in waterTexture.ts","NONE of our pack benches can see the GPU","first version poisoned the CPU MIRROR"]},
  155:{acts:[["correction","correction to point 1 of my last message",{correctionType:"self_erratum",target:"message 154 uploadView identifier"}]],caveats:["stored body is a transport erratum after shell quoting removed an identifier"]},
  161:{acts:[["request","re-baseline off my merge",{responsibility:{kind:"assigned",actor:"traffic-aa"},condition:{handling:"manual",text:"if measurements include fill-rate or shoreline frame-time"}}],["request","someone should chase them",{responsibility:{kind:"unassigned"}}]],hazards:["I've changed a SHADER","8 GL_INVALID_OPERATION"]},
  243:{acts:[["proposal","a couple of things that will help"],["proposal","when a phase appears that the plan missed"],["proposal","cli.ts done --abandoned"]],declarations:[["Nothing here is required and nothing blocks",undefined,false]]},
  248:{acts:[["request","Put your findings on the shared board",{responsibility:{kind:"assigned",actor:"traffic-56"}}],["request","State the baseline commit in the report",{responsibility:{kind:"assigned",actor:"traffic-56"}}],["proposal","Worth `cli.ts say`-ing your headline findings too"]],hazards:["a real collision the tool can't see","call graph is actively moving"]},
  249:{acts:[["proposal","that's the shape to copy"]],provenance:[["inferred_signal","worth a `cli.ts breaks`-style note when your step 3 lands"]],declarations:[["FYI, not a request",undefined,true]],hazards:["per-stage costs in their report will be stale"]},
  262:{acts:[["request","re-measure after this lands",{responsibility:{kind:"assigned",actor:"traffic-56"},condition:{handling:"manual",text:"if waterAt/isWater measured"}}],["promise","Ping me if you want me to hold terrain.ts",{commitmentMode:"refrain",condition:{handling:"manual",text:"recipient requests hold"}}],["proposal","happy to sequence"]],hazards:["DOES touch a hot query path"]},
  263:{acts:[["request","rebase rather than hold",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-56"}}],["request","fixtures on your branch will need re-recording",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-56"}}]],hazards:["we now overlap on src/gen/terrain.ts","returned Terrain object literal"]},
  267:{acts:[["promise","I'll re-apply mine on rebase",{commitmentMode:"perform"}],["question","Do river/lake COUNTS shift on seed 42 specifically?",{responsibility:{kind:"assigned",actor:"traffic-56"}}]],hazards:["Second overlap, docs/systems/terrain-water.md"],outcomes:[[1,"unassessable",269,"I did NOT touch your paragraph"],[2,"fulfilled",269,"YES, seed 42's river count moves"]]},
  268:{acts:[["correction","Correction to my last",{correctionType:"self_erratum",target:"message 267 mangled lines"}]],caveats:["stored body corrects shell transport damage"]},
  269:{acts:[["request","rebase when ready",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-56"}}],["request","RE-RECORD rather than just re-run",{responsibility:{kind:"assigned",actor:"water-sim-timberborn-56"}}]],responses:[[267,"answer","YES, seed 42's river count moves"]],hazards:["river count moves, so RE-RECORD rather than just re-run"]},
  275:{acts:[["question","can you confirm those two files are mid-rewrite",{responsibility:{kind:"assigned",actor:"traffic-56"}}],["request","when you land, re-run those two suites",{responsibility:{kind:"assigned",actor:"traffic-56"},condition:{handling:"automatic",text:"when terrain work lands",anchors:[{kind:"commit",value:"terrain work"}]}}],["promise","I am not going to touch your files",{commitmentMode:"refrain"}],["proposal","Happy to help diagnose once your work is committed",{condition:{handling:"resurface_on_related_event",text:"recipient work is committed"}}]],hazards:["Two GENERATION tests fail"],outcomes:[[1,"fulfilled",279,"NO, those files are not mid-rewrite"],[2,"fulfilled",279,"I re-ran both suites"],[3,"unassessable",279,"the regression is mine to fix"]]},
  279:{acts:[["correction","NO, those files are not mid-rewrite",{correctionType:"peer_correction",target:"mid-rewrite assumption"}],["inform","the defect is in derive/weld, not in the cull"],["promise","the regression is mine to fix",{commitmentMode:"perform"}],["handoff","tell me if you'd rather own it",{responsibility:{kind:"assigned",actor:"adela"},condition:{handling:"manual",text:"recipient prefers ownership"}}]],responses:[[275,"answer","NO, those files are not mid-rewrite"]],hazards:["the defect is in derive/weld, not in the cull"]},
  284:{acts:[["promise","I am reverting mine",{commitmentMode:"perform"}],["handoff","Yours wins",{responsibility:{kind:"assigned",actor:"adela"}}]],hazards:["STOP-COLLISION on src/gen/emit.ts","if you have the file open, re-read before you write"]},
  285:{acts:[["correction","SEED 1 STILL FAILS",{correctionType:"peer_correction",target:"termination fix"}],["proposal","Two ways out, your call"],["promise","Not touching emit.ts again",{commitmentMode:"refrain"}],["handoff","it is your file",{responsibility:{kind:"assigned",actor:"adela"}}]]},
  288:{acts:[["correction","seed 1 is STILL 12/1",{correctionType:"peer_correction",target:"reorder fix"}],["proposal","Simplest robust fix"],["promise","I have not touched emit.ts",{commitmentMode:"refrain"}]]},
  289:{acts:[["correction","I BACKED MY FIX OUT",{correctionType:"implementation_correction",target:"emit loop fix"}],["correction","I was wrong to wave it off",{correctionType:"self_erratum",target:"isHairpin assessment"}],["proposal","I would land it"],["handoff","Yours to take",{responsibility:{kind:"assigned",actor:"hopper"}}],["promise","I am not touching emit.ts again",{commitmentMode:"refrain"}]]},
  290:{acts:[["request","please stop and read this before your next edit",{responsibility:{kind:"assigned",actor:"adela"}}],["proposal","you own emit.ts, I back out entirely"],["proposal","you revert your boolean hunk"],["promise","I will do nothing until you answer",{commitmentMode:"refrain"}],["question","Which?",{responsibility:{kind:"assigned",actor:"adela"}}]],hazards:["WE ARE BOTH WRITING src/gen/emit.ts RIGHT NOW"],outcomes:[[1,"fulfilled",291,"ANSWERING"],[2,"fulfilled",291,"I take emit.ts, you back out"],[4,"fulfilled",291,"I take emit.ts"],[5,"fulfilled",291,"ANSWERING"]]},
  291:{acts:[["handoff","I take emit.ts, you back out",{responsibility:{kind:"assigned",actor:"adela"}}],["request","Please delete your isHairpin + HAIRPIN_GAP_M block",{responsibility:{kind:"assigned",actor:"hopper"}}],["correction","my claim that 'no cull pass ever sees 164, measured with 8 passes' was WRONG",{correctionType:"self_erratum",target:"message 289 measurement"}],["correction","your isHairpin comment now repeats it",{correctionType:"peer_correction",target:"isHairpin comment"}],["request","KEEP YOUR PREDICATE THOUGH",{responsibility:{kind:"assigned",actor:"hopper"}}],["request","I would like it recorded",{responsibility:{kind:"assigned",actor:"hopper"}}],["proposal","If seed 1 goes green on the loop fix alone I would rather ship that",{condition:{handling:"automatic",text:"seed 1 passes",anchors:[{kind:"test",value:"seed 1"}]}}],["promise","will report the numbers either way",{commitmentMode:"perform"}],["promise","if it does NOT go green, your predicate is the fallback and I will ask for it",{commitmentMode:"perform",condition:{handling:"automatic",text:"seed 1 does not pass",anchors:[{kind:"test",value:"seed 1"}]}}]],responses:[[290,"answer","I take emit.ts, you back out"]],outcomes:[[2,"fulfilled",292,"my isHairpin + HAIRPIN_GAP_M block is deleted"],[8,"fulfilled",295,"MY LOOP FIX DOES NOT WORK"]]},
  292:{acts:[["promise","I'm out of it and back on terrain",{commitmentMode:"refrain"}],["request","ship that alone",{responsibility:{kind:"assigned",actor:"adela"},condition:{handling:"automatic",text:"loop fix makes seed 1 green",anchors:[{kind:"test",value:"seed 1"}]}}],["request","don't add my predicate",{responsibility:{kind:"assigned",actor:"adela"},condition:{handling:"automatic",text:"loop fix makes seed 1 green",anchors:[{kind:"test",value:"seed 1"}]}}],["request","whatever fixes seed 1 needs to be robust to the geometry lottery",{responsibility:{kind:"assigned",actor:"adela"}}],["promise","I'll re-run genPolicies + junctionSliver after my change and tell you",{commitmentMode:"perform",condition:{handling:"resurface_on_related_event",text:"after erosion change",anchors:[{kind:"work_item",value:"erosion change"}]}}]],responses:[[291,"accept","Done — my isHairpin + HAIRPIN_GAP_M block is deleted"]],hazards:["robust to the geometry lottery, not tuned to stroke 164"]},
  295:{acts:[["correction","MY LOOP FIX DOES NOT WORK AND I HAVE REVERTED IT",{correctionType:"implementation_correction",target:"emit loop fix"}],["handoff","Take the predicate back",{responsibility:{kind:"assigned",actor:"hopper"}}],["promise","I am not going to guess a fifth time",{commitmentMode:"refrain"}],["proposal","land your isHairpin"],["proposal","derive-disagreement chased afterwards",{responsibility:{kind:"unassigned"}}]]},
  323:{acts:[["inform","the COUNT moves with generation and the FAILURE does not"],["inform","my 2fc431b changes generated heights slightly"],["inform","I have no accumulating-arclength loops"]],hazards:["underlying dead-end-stub bug in stroke deletion is the real defect"]},
  399:{acts:[["correction","Background tasks self-notify",{correctionType:"peer_correction",target:"polling behaviour"}],["proposal","the harness has Monitor with an until-loop"]],hazards:["you `cat` a PARTIAL file and treat it as the final answer","blocks your turn for up to 10 minutes"]}
};

// Status/information moves that remain independently useful after the requests,
// promises and hazards are removed. Kept separate so they cannot become the v1
// dump bucket: each entry has one explicit decisive phrase.
const INFORM:Record<number,string>={
  9:"I've moved off master into worktree",35:"nothing of mine in test/",36:"I've COMMITTED test/networkWatchdog.test.ts",38:"no uncommitted work in test/ right now",
  40:"I'm in the WORKTREE, not the main tree",70:"test/camera.test.ts now exists",95:"P3 has landed",97:"your P3 files (incl. the new wateractive.ts) don't exist here yet",
  109:"I've been asked to micro-optimize",110:"All P0-P3 water work is ALREADY MERGED",111:"Baseline recorded on master",112:"My fix is on the SCHEDULING/prevDepth side only",
  122:"packBand work is LANDED on master",132:"I have ALREADY COMMITTED edits to it on master",133:"Root cause of the user's bug",136:"Merged to master as 9addb42",
  141:"Fixed on master as bce6afd",146:"What I've landed since your all-clear",154:"P0b is done",161:"I've changed a SHADER",
  248:"water-sim-timberborn-56 has src/gen/hydrology.ts UNCOMMITTED-MODIFIED",249:"traffic-56 is currently PROFILING src/gen/hydrology.ts",262:"I'm in worktree water-sim-timberborn making the dynamic water sim the default",263:"I'm about to commit to MASTER",
  267:"I rewrote ONE paragraph",269:"Landed on master as 517b34d",275:"I just merged worktree-old-core-retirement to master",279:"I re-ran both suites",
  284:"generation ends with live self-loops=0 on seed 1",285:"5 of 6 seeds clean",288:"final doc has 143 roads",289:"WHAT IS ESTABLISHED",
  290:"the file currently does not typecheck",291:"My boolean hunk is now COMPLETE",292:"typecheck' is CLEAN on the whole project",295:"instrumenting the loop prints",
  323:"fails at 2fc431b~1 as well"
};

function evidence(id:number, quote:string, messageId=id):Evidence {
  const body=byId.get(messageId)?.body; if(body===undefined) throw new Error(`missing source ${messageId}`);
  const start=body.indexOf(quote); if(start<0) throw new Error(`#${id}: quote not found in #${messageId}: ${quote}`);
  return {confidence:"high",spans:[{messageId,start,end:start+quote.length,quote}]};
}
const PRIORITY:Record<number,"normal"|"important"|"urgent">={8:"important",9:"normal",35:"important",36:"normal",37:"important",38:"normal",39:"urgent",40:"important",70:"normal",71:"normal",95:"important",97:"important",109:"important",110:"urgent",111:"important",112:"important",122:"important",132:"urgent",133:"important",136:"important",141:"important",146:"important",154:"urgent",155:"normal",161:"important",243:"normal",248:"important",249:"normal",262:"important",263:"important",267:"normal",268:"normal",269:"urgent",275:"urgent",279:"important",284:"urgent",285:"important",288:"important",289:"urgent",290:"urgent",291:"urgent",292:"important",295:"urgent",323:"normal",399:"important"};
function annotation(id:number):Annotation {
  const src=byId.get(id)!; const spec=S[id]; if(!spec) throw new Error(`missing spec ${id}`);
  const actSpecs=[...(spec.acts??[]),...(INFORM[id]?[(["inform",INFORM[id]!] as A)]:[])];
  const acts=actSpecs.map(([type,quote,over],i):Act=>({
    id:`${id}-a${i+1}`,type,author:src.from,recipients:[src.to],responsibility:type==="promise"?{kind:"assigned",actor:src.from}:{kind:"none"},evidence:evidence(id,quote),...over,
  }));
  const p=PRIORITY[id]; if(!p) throw new Error(`missing v2 priority for ${id}`);
  const explicitOutcomes=(spec.outcomes??[]).map(([actIndex,value,messageId,q])=>({
    actId:`${id}-a${actIndex}`,value,
    evidence:{...(["unresolved","unassessable"].includes(value)?acts[actIndex-1]!.evidence:evidence(id,q,messageId)),...(["unresolved","unassessable"].includes(value)?{ambiguity:"The available corpus does not establish a definitive resolution."}:{})},
  }));
  const resolved=new Set(explicitOutcomes.map(x=>x.actId));
  const fallbackOutcomes=acts.filter(a=>["question","request","promise","handoff"].includes(a.type)&&!resolved.has(a.id)).map(a=>({
    actId:a.id,value:"unassessable" as const,
    evidence:{...a.evidence,ambiguity:"The corpus does not establish that the condition fired or how this act resolved."},
  }));
  return {id,acts,
    hazards:(spec.hazards??[]).map((q,i)=>({id:`${id}-h${i+1}`,subject:q,evidence:evidence(id,q)})),
    provenance:(spec.provenance??[]).map(([kind,q],i)=>({id:`${id}-p${i+1}`,kind,summary:q,evidence:evidence(id,q)})),
    declarations:(spec.declarations??[]).map(([q,appliesToActId,conflict],i)=>({id:`${id}-d${i+1}`,declared:q,appliesToActId,conflict,evidence:evidence(id,q)})),
    responses:(spec.responses??[]).map(([respondsToMessageId,disposition,q])=>({respondsToMessageId,disposition,evidence:evidence(id,q)})),
    priorities:[{recipient:src.to,value:p,evidence:evidence(id,src.body.slice(0,Math.min(src.body.length,80)))}],
    actOutcomes:[...explicitOutcomes,...fallbackOutcomes] as Annotation["actOutcomes"],
    sourceCaveats:spec.caveats??[],
  };
}
const result=analysed.map(annotation);
const diagnostics=validateAnnotations(result,new Map(source.map(x=>[x.id,x])),analysed);
if(diagnostics.length) throw new Error(diagnostics.map(x=>`${x.path}: ${x.message}`).join("\n"));
await Bun.write(`${ROOT}/audit-v2-primary.json`,JSON.stringify(result,null,2)+"\n");
console.log(`wrote ${result.length} validated annotations`);
